---
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load packages
library(tidyverse)
library(shiny)
library(DT)
library(shinyWidgets)
library(magick)
library(rvest)
library(pdftools)
library(janitor)

# Read in data
allGames <- read.csv("C:/Users/brown/Documents/GitHub/UVABaseballDashboard/2023 Season Data.csv") %>%
  mutate(opponent = paste(BatterTeam, sub("/2023", "", Date)))

virginia <-  allGames %>%
  filter(PitcherTeam == 'Virginia') %>%
  select(-c(50:167))
```


```{r setup, include=FALSE}
# Get a player's picture
find_pic <- function(name){
  tmpfile <- read_html(paste("https://virginiasports.com/player/", 
                             sub(" ", "-", name) %>% tolower(), 
                             "/",
                             sep = "")) %>%
      html_nodes(xpath = '//*[@class="bio-info"]') %>%
      html_elements("img") %>%
      html_attr("src") %>%
      image_read() %>%
      image_write(tempfile(fileext='jpg'), format = 'jpg')
    
    # Return a list
    list(src = tmpfile, contentType = "image/jpeg", width = 200, height = 260)
}

# Get a player's stats for their profile
raw_text <- map("https://static.virginiasports.com/custompages/sports/m-basebl/stats/2022-2023/SeasonStats.pdf?_gl=1*11rpgpg*_ga*MTg1NjExNzA0NC4xNjgwMTg0ODQy*_ga_X9RVV1P9QW*MTY4MTkyNDQ1Ni4xMC4xLjE2ODE5MjQ4NDUuNjAuMC4w&_ga=2.154379455.640199771.1681924456-1856117044.1680184842", 
                pdf_text)[[1]]
pit_stats <- str_split(raw_text, "\n")[[1]][46:63] %>%
  str_squish() %>%
  sub(".*?\\d ", "", x = .) %>%
  sub(" ", "", x = .) %>%
  sub("Playerera", "Player era", x = .) %>%
  data.frame() %>%
  slice(-5) %>%
  row_to_names(row_number = 1) %>%
  separate(names(.), into = str_split(names(.), " ")[[1]], sep = " ") %>%
  mutate(Player = gsub('([[:upper:]])', ' \\1', Player),
         Player = trimws(Player)) 

find_stats <- function(name){
  pit_stats %>%
    filter(Player == name) %>%
    select(-c(sho, '2b', '3b', bk, sfa, sha)) %>%
    mutate("K/9" = (9*as.numeric(so)/as.numeric(ip)) %>% round(2),
           "BB/9" = (9*as.numeric(bb)/as.numeric(ip)) %>% round(2),
           "HR/9" = (9*as.numeric(hr)/as.numeric(ip)) %>% round(2))
}

# Player tab function
playerTab <- function(name){
  tabPanel(title = name, value = name,
                        fluidRow(
                          column(2,
                                 div(imageOutput(paste0("pic_", 
                                                        paste0(unlist(str_extract_all(name, "[:upper:]")), 
                                                               collapse = ""))), style = "height:294px")),
                          column(9,
                                 div(dataTableOutput(paste0("stats_", 
                                                        paste0(unlist(str_extract_all(name, "[:upper:]")), 
                                                               collapse = ""))), style = "font-size: 95%"))),
                        # Put in options for what to look at
                        tabsetPanel(tabPanel(title = "Overview",
                                             # Add in brooks baseball summary type thing
                                             ),
                                    tabPanel(title = "Scatter Plots",
                                             # Add in pie charts plus table of results
                                             fluidRow(column(2, uiOutput(paste0(
                                               "xaxis", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "sp")), 
                                                        uiOutput(paste0(
                                               "yaxis", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                               collapse = ""), "sp"))),
                                                      column(6, plotOutput(paste0(
                                               "sp_plot_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = "")))),
                                                      column(4, 
                                                             div(dataTableOutput(paste0(
                                               "sp_table_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""))),
                                                                 style = "font_size: 80%")))),
                                    tabPanel(title = "Zone Profile",
                                             # Add in counts
                                             fluidRow(column(2, 
                                                             uiOutput(paste0(
                                               "ptype", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "zp")), 
                                                             uiOutput(paste0(
                                               "bhand", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "zp"))),
                                                      column(6, 
                                                             plotOutput(paste0(
                                               "zp_plot_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = "")))))),
                                    tabPanel(title = "Tables",
                                             # Add in batter handedness that applies to both
                                             fluidRow(p("Movement, Release, and Outcomes", 
                                                        style = "text-align: center; font-weight: bold; font-size: 130%; 
                                                        padding-top: 25px; padding-bottom: 10px"),
                                                      div(dataTableOutput(paste0(
                                               "tab_moveout_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""))), 
                                                          style = "font-size: 85%")),
                                             fluidRow(p("Usage", 
                                                        style = "text-align: center; font-weight: bold; font-size: 130%; 
                                                        padding-top: 25px; padding-bottom: 10px"),
                                                      div(dataTableOutput(paste0(
                                               "tab_usage_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""))), 
                                                          style = "font-size: 90%"))),
                                    tabPanel(title = "In-Game Durability", value = "durab",
                                             fluidRow(column(2, 
                                                             uiOutput(paste0(
                                               "ptype", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "durab"))),
                                                      column(6, 
                                                             plotOutput(paste0(
                                               "pc_graph_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = "")))),
                                                      column(4, 
                                                             div(dataTableOutput(paste0(
                                               "pc_table_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""))), 
                                                                 style = "font-size: 80%")))),
                                    tabPanel(title = "Game-to-game Performance",
                                             fluidRow(column(2, 
                                                             uiOutput(paste0(
                                               "ptype", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "gtg")), 
                                                             uiOutput(paste0(
                                               "metric", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""), "gtg"))),
                                                      column(6, 
                                                             plotOutput(paste0(
                                               "gtg_graph_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = "")))),
                                                      column(4, div(dataTableOutput(paste0(
                                               "gtg_table_", paste0(unlist(str_extract_all(name,"[:upper:]")), 
                                                              collapse = ""))), 
                                                                    style = "font-size: 80%"))))
                                    )
                        )
}

```

```{r ui and server, echo = FALSE}
ui <- fluidPage(
  titlePanel("UVA Baseball Pitching Dashboard"),
  tags$head(
    tags$style(
      HTML(
        "
        
        /* Change the background color of the navbar */
        .navbar {
          background-color: #E57200;
        }
        
        /* Change the color of the text in the navbar */
        .navbar-default .navbar-nav > li > a {
          color: white;
        }
        
        /* Change the color of the active tab */
        .navbar-default .navbar-nav > .active > a,
        .navbar-default .navbar-nav > .active > a:focus,
        .navbar-default .navbar-nav > .active > a:hover {
          background-color: #232D4B;
          color: white;
        }
        "
      )
    )
  ),
  
  navbarPage(
    title = " ", id = "Dash",
    ### Tab 1- Game Summaries
    tabPanel(title = "Game Summaries",
             sidebarLayout(
               sidebarPanel(width = 4,
                            selectizeInput("pitcher", "Select a Pitcher", 
                                           choices = unique(virginia$Pitcher), 
                                           options = list(placeholder = 'Please select an option below',
                                                          onInitialize = I('function() { this.setValue(""); }'))),
                            
                            uiOutput("Opponent"),
                            uiOutput("PType1"),
                            uiOutput("bHand"),
                            uiOutput("Outcome")),
               
               mainPanel(width = 8,
                         conditionalPanel("input.PitchType1 != '' & input.bhand != '' & input.outcome != ''",
                                div(plotOutput("pitchZone")))
                         )),
             
             fluidRow(
               column(12,
                      conditionalPanel("input.PitchType1 != '' & input.bhand != '' & input.outcome != ''",
                                       div(DT::dataTableOutput("mytable"), style = "font-size: 70%; width: 100%"))
                      )
               )
             
             
             ),
    ### Tab 2- Player profiles(Should I add in a header to each?)
    navbarMenu(title = "Pitcher Profiles",
               # Put in sub tabs for each player
               playerTab("Connelly Early"),
               playerTab("Kevin Jaxel")
               )
    )
  )

server = function(input, output) {
  ##################################################################################################################
  ### Tab 1- Game Summaries
  # Select opponent bar
  output$Opponent <- renderUI({
    conditionalPanel("input.pitcher != '' ",
                     pickerInput("opponent", "Game", 
                                 choices = c(virginia %>% 
                                               filter(Pitcher %in% input$pitcher) %>% 
                                               pull(opponent) %>% 
                                               unique()),
                                 options = list('actions-box' = TRUE),
                                 multiple = TRUE))
  })
  # Select Pitch type bar
  output$PType1 <- renderUI({
    conditionalPanel("input.opponent != '' ",
                     pickerInput("PitchType1", "Pitch Type", 
                                 choices = virginia %>% 
                                   filter(Pitcher %in% input$pitcher,
                                          opponent %in% input$opponent) %>% 
                                   pull(TaggedPitchType) %>% 
                                   unique(), 
                                 options = list('actions-box' = TRUE),
                                 multiple = TRUE))
  })
  # Select batter handedness bar
  output$bHand <- renderUI({
    conditionalPanel("input.PitchType1 != '' ",
                     pickerInput("bhand", "Batter handedness", 
                                 choices = c("Right", "Left"), 
                                 selected = c("Right", "Left"),
                                 options = list('actions-box' = TRUE),
                                 multiple = TRUE))
  })
  # Select outcome bar
  output$Outcome <- renderUI({
    conditionalPanel("input.PitchType1 != '' ",
                     pickerInput("outcome", "Outcome", 
                                 choices = virginia %>% 
                                   filter(Pitcher %in% input$pitcher,
                                          opponent %in% input$opponent,
                                          TaggedPitchType %in% input$PitchType1) %>% 
                                   mutate(PitchCall = case_when(
                                     PitchCall == "InPlay" ~ PlayResult,
                                     PitchCall != "InPlay" ~ PitchCall)) %>%
                                   pull(PitchCall) %>% 
                                   unique(), 
                                 selected = virginia %>% 
                                   filter(Pitcher %in% input$pitcher,
                                          opponent %in% input$opponent,
                                          TaggedPitchType %in% input$PitchType1) %>% 
                                   mutate(PitchCall = case_when(
                                     PitchCall == "InPlay" ~ PlayResult,
                                     PitchCall != "InPlay" ~ PitchCall)) %>%
                                   pull(PitchCall) %>% 
                                   unique(),
                                 options = list('actions-box' = TRUE),
                                 multiple = TRUE))
  })
  # Zone plot of pitches
  output$pitchZone <- renderPlot({
    if(is.null(input$PitchType1)){
      return(NULL)
    }
    
    else {
      virginia %>%
        mutate(PitchCall = case_when(
          PlayResult == "Single" | PlayResult == "Double" | PlayResult == "Triple" ~ "Hit",
          PlayResult == "Out" | PlayResult == "FieldersChoice" | PlayResult == "Error" ~ "Out",
          PitchCall == "InPlay" ~ PlayResult,
          PitchCall != "InPlay" ~ PitchCall)) %>%
        filter(PitchCall != "",
               Pitcher %in% input$pitcher,
               opponent %in% input$opponent,
               TaggedPitchType %in% input$PitchType1,
               PitchCall %in% input$outcome,
               BatterSide %in% input$bhand) %>%
        ggplot(aes(x = PlateLocSide, y = PlateLocHeight)) +
        geom_point(aes(color = PitchCall), na.rm = TRUE) +
        xlim(-2.5, 2.5) +
        theme_bw() +
        labs(y = "Pitch Height(ft)", x = "Pitch Horizontal Location(ft) from Pitcher POV", color = "Outcome") +
        geom_path(data = data.frame(x = c(-.8, -.8, .8, .8, -.8),
                                    y = c(1.6, 3.5, 3.5, 1.6, 1.6)), 
                  aes(x = x, y = y)) +
        facet_grid(. ~ TaggedPitchType) +
        coord_equal()
    }
  })
  # Pitch results table
  output$mytable <- DT::renderDataTable({
    if(is.null(input$PitchType1)){
      return(NULL)
    }
    
    else {
      datatable(virginia %>%
         filter(PitchCall != "",
                Pitcher %in% input$pitcher,
                opponent %in% input$opponent,
                BatterSide %in% input$bhand) %>%
         group_by(Pitcher, TaggedPitchType) %>%
         summarize('Sitting Velo' = paste(round(quantile(RelSpeed, .25), 1), 
                                          "-",
                                          round(quantile(RelSpeed, .75), 1)),
                   'Max Velo' = round(max(RelSpeed), 1),
                   'Total Pitches' = n(),
                   Strikes = sum(PitchCall %in% c("StrikeCalled", "StrikeSwinging", "FoulBall", "InPlay")),
                   Balls = sum(PitchCall %in% c("BallCalled", "HitByPitch", "BallinDirt", "BallIntentional")),
                   Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
                   Takes = sum(PitchCall %in% c("StrikeCalled", "BallCalled", "HitByPitch", "BallinDirt")),
                   SwStr = sum(PitchCall == "StrikeSwinging"),
                   WhiffPerc = 100*round(SwStr/Swings, 3),
                   HR = sum(PlayResult == "HomeRun"),
                   BABIP = (sum(PlayResult %in% c("Single", "Double", "Triple"))/
                     sum(PlayResult %in% c("Single", "Double", "Triple", "Out", "Error", "FieldersChoice") | 
                           (TaggedHitType == "Bunt" & PlayResult == "Sacrifice"))) %>% round(3),
                   .groups = "keep") %>%
         rename(Name = Pitcher, 'Pitch Type' = TaggedPitchType, 'Whiff %' = WhiffPerc),
         options = list(scrollX = T))
    }
  })
  
  ################################################################################################################
  ### Tab 2- Profiles
  # Player profile pics
  observe({
    output[[paste0("pic_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderImage({
                     find_pic(input$Dash)
                     }, deleteFile = TRUE)
  })
  # Player stats
  observe({
    output[[paste0("stats_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                     datatable(find_stats(input$Dash), rownames = FALSE)
                     })
  })
  ##########################
  ### Inner tab 1- Durability
  # Select pitch type
  observe({
    output[[
      paste0("ptype", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "durab")]] <- renderUI({
        selectizeInput(paste0("ptype", 
                              paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                              "durab"), 
                       "Pitch type", 
                       choices = c(virginia %>% 
                                     filter(Pitcher %in% sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>% 
                                     pull(TaggedPitchType) %>% 
                                     unique()), 
                       options = list('actions-box' = TRUE))
        })
    })
  # Pitch count velo graph
  observe({
    output[[paste0("pc_graph_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderPlot({
                     allGames %>%
                       mutate(ct = 1) %>%
                       group_by(Pitcher, Date) %>%
                       mutate(pc = cumsum(ct)) %>%
                       ungroup() %>%
                       mutate(pc_range = ceiling(pc/5),
                              pc_range = cut(pc,
                                              seq(0, 200, 5),
                                              labels = FALSE)) %>%
                       filter(TaggedPitchType == input[[paste0("ptype", 
                                                               paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                      collapse = ""), "durab")]], 
                              Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                       group_by(Pitcher, pc_range) %>%
                       summarize(avg_velo = mean(RelSpeed, na.rm = TRUE),
                                 ct = n(), 
                                 .groups = "keep") %>%
                       ungroup() %>%
                       mutate(pc_range2 = paste((pc_range - 1) * 5 + 1, pc_range * 5, sep = "-"),
                              pc_range2 = factor(pc_range2, levels = pc_range2)) %>%
                       ggplot(aes(x = pc_range2, y = avg_velo, group = 1)) +
                       geom_point() +
                       geom_line() +
                       theme_bw() +
                       labs(title = paste(input$Dash, "Average", 
                                          input[[paste0("ptype", 
                                                        paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "durab")]], 
                                          "Velo by pitch count"), 
                            x = "Pitch Count", 
                            y = paste(input[[paste0("ptype", 
                                                    paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                           collapse = ""), "durab")]], 
                                      "Velo(mph)")) +
                       theme(axis.text.x = element_text(size = 11))  
                     })
  })
  # Pitch count velo table
  observe({
    output[[paste0("pc_table_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                     allGames %>%
                       mutate(ct = 1) %>%
                       group_by(Pitcher, Date) %>%
                       mutate(pc = cumsum(ct)) %>%
                       ungroup() %>%
                       mutate(pc_range = ceiling(pc/5),
                              pc_range = cut(pc,
                                              seq(0, 200, 5),
                                              labels = FALSE)) %>%
                       filter(TaggedPitchType == input[[paste0("ptype", 
                                                               paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                      collapse = ""), "durab")]], 
                              Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                       group_by(Pitcher, pc_range) %>%
                       summarize(avg_velo = round(mean(RelSpeed), 1),
                                 n = n(), 
                                 .groups = "keep") %>%
                       ungroup() %>%
                       mutate(pc_range = paste((pc_range - 1) * 5 + 1, pc_range * 5, sep = "-")) %>%
                       rename("Pitch Count Range" = pc_range,
                              "Average Velo" = avg_velo,
                              "Number Thrown" = n)
                     })
    })
  ### Inner tab 2- Game to game
  # Select pitch type
  observe({
    output[[
      paste0("ptype", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "gtg")]] <- renderUI({
        selectizeInput(paste0("ptype", 
                              paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                              "gtg"), 
                       "Pitch type", 
                       choices = c(virginia %>% 
                                     filter(Pitcher %in% sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>% 
                                     pull(TaggedPitchType) %>% 
                                     unique()))
        })
    })
  # Select metric
  observe({
    output[[
      paste0("metric", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "gtg")]] <- renderUI({
        selectizeInput(paste0("metric", 
                              paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                              "gtg"), 
                       "Metric", 
                       choices = c("Velocity" = "Velocity", 
                                   "Spin Rate" = "SpinRate", 
                                   "Usage" = "Usage"))
        })
    })
  # Game-to-game graph
  observe({
    output[[paste0("gtg_graph_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderPlot({
                     allGames %>%
                       filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                       group_by(Pitcher, Date, opponent, TaggedPitchType) %>%
                       summarize(Velocity = mean(RelSpeed, na.rm = TRUE), 
                                 SpinRate = mean(SpinRate, na.rm = TRUE),
                                 ct = n(),
                                 .groups = "drop_last") %>%
                       mutate(Usage = 100*ct/sum(ct)) %>%
                       ungroup() %>%
                       filter(TaggedPitchType == input[[paste0("ptype", 
                                                               paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                      collapse = ""), "gtg")]]) %>%
                       arrange(mdy(Date)) %>%
                       mutate(opponent = factor(opponent, levels = opponent)) %>%
                       ggplot(aes_string(x = "opponent", 
                                  y = input[[paste0("metric", 
                                                    paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                           collapse = ""), "gtg")]]
                                  )) +
                       geom_point() +
                       geom_line(aes(group = 1)) +
                       theme_bw() + 
                       theme(axis.text.x = element_text(angle = 15, hjust = .5, vjust = .5)) +
                       labs(title = paste(input$Dash, "Average", 
                                          input[[paste0("ptype", 
                                                        paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "gtg")]], 
                                          input[[paste0("metric", 
                                                        paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "gtg")]],
                                          "by Game"), 
                            x = "Opponent", 
                            y = paste(input[[paste0("ptype", 
                                                    paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                           collapse = ""), "gtg")]], 
                                      input[[paste0("metric", 
                                                        paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "gtg")]]))
                     })
    })
  # Game-to-game table
  observe({
    output[[paste0("gtg_table_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                     allGames %>%
                       filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                       group_by(Pitcher, Date, opponent, TaggedPitchType) %>%
                       summarize(Velocity = mean(RelSpeed, na.rm = TRUE) %>% round(1), 
                                 SpinRate = mean(SpinRate, na.rm = TRUE) %>% round(0),
                                 ct = n(),
                                 .groups = "drop_last") %>%
                       mutate(Usage = (100*ct/sum(ct)) %>% round(1)) %>%
                       ungroup() %>%
                       filter(TaggedPitchType == input[[paste0("ptype", 
                                                               paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                      collapse = ""), "gtg")]]) %>%
                       arrange(mdy(Date)) %>%
                       select(opponent, ct, 
                              input[[paste0("metric", 
                                            paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                   collapse = ""), "gtg")]]) %>%
                       rename("Number Thrown" = ct,
                              "Opponent" = opponent) 
                     })
  })
  ### Inner tab 3- Zone profile
  # Select pitch type
  observe({
    output[[
      paste0("ptype", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "zp")]] <- renderUI({
        selectizeInput(paste0("ptype", 
                              paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                              "zp"), 
                       "Pitch type", 
                       choices = c(virginia %>% 
                                     filter(Pitcher %in% sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>% 
                                     pull(TaggedPitchType) %>% 
                                     unique()))
      })
  })
  # Select batter handedness
  observe({
    output[[
      paste0("bhand", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "zp")]] <- renderUI({
        pickerInput(paste0("bhand", 
                           paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                           "zp"), 
                    "Batter handedness", 
                    choices = c("Right", "Left"), 
                    selected = c("Right", "Left"),
                    options = list('actions-box' = TRUE),
                    multiple = TRUE)
      })
  })
  # Zone plot
  observe({
    output[[paste0("zp_plot_", 
                   paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderPlot({
                     locs <- virginia %>%
                       filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash),
                              TaggedPitchType == input[[paste0("ptype", 
                                                               paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                      collapse = ""), "zp")]],
                              BatterSide %in% input[[paste0("bhand", 
                                                          paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                 collapse = ""), "zp")]]) %>%
                       mutate(x2 = (1.6/5)*floor((PlateLocSide)/(1.6/5)),
                              y2 = 1.79 + (1.9/5)*floor((PlateLocHeight - 1.79)/(1.9/5))) %>%
                       group_by(x2, y2) %>%
                       summarize(ct = n(), .groups = "drop") %>%
                       mutate(perc = 100*ct/sum(ct))
                       
                       locs %>%
                         ggplot(aes(x = x2, y = y2)) +
                         geom_tile(aes(fill = perc)) +
                         xlim(-2.5, 2.5) +
                         ylim(0, 5) +
                         geom_path(data = data.frame(x = c(-.8, -.8, .8, .8, -.8),
                                                     y = c(1.6, 3.5, 3.5, 1.6, 1.6)), 
                                   aes(x = x, y = y), color = "red", size = 1.4) +
                         scale_fill_gradient(low = '#232D4B', high = '#E57200', 
                                             limits = c(0, max(locs$perc)), name = "Percentage of Pitches") +
                         theme_bw() + 
                         theme(panel.background = element_rect(fill = '#232D4B', color = '#232D4B'),
                               panel.grid.major = element_blank(), 
                               panel.grid.minor = element_blank()) + 
                         labs(x = "Pitch Location(Pitcher POV)", y = "Pitch Height") 
                       })
  })
    ### Inner tab 4- Scatter plots
    # Select x-axis variable
    observe({
      output[[
        paste0("xaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "sp")]] <- renderUI({
          selectizeInput(paste0("xaxis", 
                                paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                                "sp"), 
                         "X-axis Variable", 
                         choices = c("Horizontal Movement",
                                     "Vertical Movement",
                                     "Spin Rate",
                                     "Spin Axis",
                                     "Velocity",
                                     "Horizontal Release Point",
                                     "Vertical Release Point"),
                         selected = "Horizontal Release Point")
        })
      })
    
    # Select y-axis variable
    observe({
      output[[
        paste0("yaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), "sp")]] <- renderUI({
          selectizeInput(paste0("yaxis", 
                                paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""), 
                                "sp"), 
                         "Y-axis Variable", 
                         choices = c("Horizontal Movement",
                                     "Vertical Movement",
                                     "Spin Rate",
                                     "Spin Axis",
                                     "Velocity",
                                     "Horizontal Release Point",
                                     "Vertical Release Point"),
                         selected = "Vertical Release Point")
          })
      })
    
    # Make pitch graph
    observe({
      output[[paste0("sp_plot_", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- 
        renderPlot({
          allGames %>%
            select(Pitcher, RelSpeed, HorzBreak, InducedVertBreak, SpinRate, SpinAxis, RelSide, 
                   RelHeight, TaggedPitchType) %>%
            drop_na(RelSpeed, HorzBreak, InducedVertBreak, SpinRate, SpinAxis, RelSide, RelHeight) %>%
            rename(Velocity = RelSpeed,
                   "Horizontal Movement" = HorzBreak,
                   "Vertical Movement" = InducedVertBreak,
                   "Spin Rate" = SpinRate,
                   "Spin Axis" = SpinAxis,
                   "Horizontal Release Point" = RelSide,
                   "Vertical Release Point" = RelHeight) %>%
            filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
            ggplot(aes(x = !!sym(input[[paste0("xaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "sp")]]), 
                       y = !!sym(input[[paste0("yaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                               collapse = ""), "sp")]]), 
                       color = TaggedPitchType)) +
            geom_point() +
            theme_bw()
        })
      })
    
    # Make corresponding table
    observe({
      output[[paste0("sp_table_", 
                     paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                       if(is.null(input$Dash)){
                         return(NULL)}
                       else{
                         allGames %>%
                           filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                           drop_na(RelSpeed, HorzBreak, InducedVertBreak, SpinRate) %>%
                           group_by(TaggedPitchType) %>%
                           summarize(Velocity = round(mean(RelSpeed, na.rm = T), 1),
                                     "Spin Rate" = round(mean(SpinRate, na.rm = T), 1),
                                     "Spin Axis" = round(mean(SpinAxis, na.rm = T), 1),
                                     "Horizontal Movement" = round(mean(HorzBreak, na.rm = T), 1),
                                     "Vertical Movement" = round(mean(InducedVertBreak, na.rm = T), 1),
                                     "Horizontal Release Point" = round(mean(RelSide, na.rm = T), 1),
                                     "Vertical Release Point" = round(mean(RelHeight, na.rm = T), 1)) %>%
                           select(TaggedPitchType, 
                                  input[[paste0("xaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                collapse = ""), "sp")]],
                                  input[[paste0("yaxis", paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), 
                                                                collapse = ""), "sp")]]) %>%
                           rename("Pitch Type" = TaggedPitchType)
                         }
                       })
      })
    ### Inner tab 5- Tables
    # Movement and Outcomes
    observe({
      output[[paste0("tab_moveout_", 
                     paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                       allGames %>%
                         filter(PitchCall != "",
                         TaggedPitchType != "",
                         Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                         group_by(Pitcher, TaggedPitchType) %>%
                         summarize(Count = n(),
                         Velo = paste(round(quantile(RelSpeed, .25), 1), 
                                      "-", round(quantile(RelSpeed, .75), 1)),
                         'Vertical Break' = round(mean(InducedVertBreak), 2),
                         'Horizontal Break' = round(mean(HorzBreak), 2),
                         'Vertical Release' = round(mean(RelHeight, na.rm = T), 2),
                         'Horizontal Release' = round(mean(RelSide, na.rm = T), 2),
                         Strikes = sum(PitchCall %in% c("StrikeCalled", "StrikeSwinging", "FoulBall")),
                         'Strike %' = 100*round(Strikes/Count, 3),
                         Balls = sum(PitchCall %in% c("BallCalled", "BallinDirt", "BallIntentional")),
                         'Ball %' = 100*round(Balls/Count, 3),
                         BIP = sum(PlayResult %in% c("Single", "Double", "Triple", "Out", 
                                                     "Error", "FieldersChoice") | 
                                     (TaggedHitType == "Bunt" & PlayResult == "Sacrifice")),
                         'BIP %' = (100*BIP/Count) %>% round(1),
                         Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
                         'Swing %' = 100*round(Swings/Count, 3),
                         Fouls = sum(PitchCall == 'FoulBall'),
                          'Foul %' = 100*round(Fouls/Swings, 3),
                         SwStr = sum(PitchCall == "StrikeSwinging"),
                         'Whiff %' = 100*round(SwStr/Swings, 3),
                         "GB %" = (100*sum(TaggedHitType == "GroundBall")/BIP) %>% round(1),
                         "FB %" = (100*sum(TaggedHitType == "FlyBall")/BIP) %>% round(1),
                         "PU %" = (100*sum(TaggedHitType == "Popup")/BIP) %>% round(1),
                         "LD %" = (100*sum(TaggedHitType == "LineDrive")/BIP) %>% round(1),
                         HR = sum(PlayResult == "HomeRun"),
                         BABIP = (sum(PlayResult %in% c("Single", "Double", "Triple"))/
                           sum(PlayResult %in% c("Single", "Double", "Triple", "Out", "Error", "FieldersChoice") | 
                                 (TaggedHitType == "Bunt" & PlayResult == "Sacrifice"))) %>% round(3),
                         .groups = "drop") %>%
                         mutate(Usage = (100*Count/sum(Count)) %>% round(1)) %>%
                         relocate(Usage, .after = Count) %>%
                         rename(Name = Pitcher, 'Pitch Type' = TaggedPitchType, "Percentage Thrown" = Usage) %>%
                         select(-c(Strikes, Balls, Swings, BIP, Fouls, SwStr)) %>%
                         datatable(container = withTags(table(
                           class = 'display',
                           thead(
                             tr(
                               th(colspan = 3, ''),
                               th(colspan = 7, 'Season Averages'),
                               th(colspan = 4, 'Percentages of All Pitches'),
                               th(colspan = 2, "Percentages of Swings"),
                               th(colspan = 4, 'Percentages of Batted Balls'),
                               th(colspan = 2, 'Results')
                             ),
                             tr(th(""), th("Name"), th("Pitch Type", style = "border-right: solid 2px;"),
                                th("Count"), th("Percentage Thrown"), th("Velo"), th("Vertical Break"), 
                                th("Horizontal Break"), th("Vertical Release"), 
                                th("Horizontal Release", style = "border-right: solid 2px;"), 
                                th("Strike %"), th("Ball %"), th("BIP%"),
                                th("Swing %", style = "border-right: solid 2px;"), 
                                th("Foul %"), th("Whiff %", style = "border-right: solid 2px;"), 
                                th("GB %"), th("FB %"), th("PU %"), th("LD %", style = "border-right: solid 2px;"),
                                th("HR"), th("BABIP"))
                             ))
                           ),
                           options = list(columnDefs = list(list(targets = "_all", className = "dt-center"))
                                          )) %>%
                         formatStyle(c(2, 9, 13, 15, 19), `border-right` = "solid 2px")
                       })
      })
    # Usage table
    observe({
      output[[paste0("tab_usage_", 
                     paste0(unlist(str_extract_all(input$Dash, "[:upper:]")), collapse = ""))]] <- renderDataTable({
                       if(is.null(input$Dash)){
                         return(NULL)}
                       else {
                         allGames %>%
                           filter(Pitcher == sub("([^ ]*) ([^ ]*)", "\\2, \\1", input$Dash)) %>%
                           mutate(CountType = case_when(
                             Balls == 0 & Strikes == 0 ~ "All Counts, Even, First Pitch",
                             Balls == Strikes & Strikes != 2 ~ "All Counts, Even",
                             Balls == Strikes & Strikes == 2 ~ "All Counts, Even, Two Strikes",
                             
                             Balls > Strikes & Strikes != 2 ~ "All Counts, Batter Ahead",
                             Balls > Strikes & Strikes == 2 ~ "All Counts, Full Count",
                             
                             Balls < Strikes & Strikes != 2 ~ "All Counts, Pitcher Ahead",
                             Balls < Strikes & Strikes == 2 ~ "All Counts, Pitcher Ahead, Two Strikes"
                             ))  %>%
                           separate_rows(CountType, sep = ", ") %>%
                           group_by(BatterSide, CountType, TaggedPitchType) %>%
                           summarize(ct = n(), .groups = "drop") %>%
                           pivot_wider(names_from = TaggedPitchType, values_from = ct) %>%
                           replace(is.na(.), 0) %>%
                           rowwise() %>%
                           mutate(total = sum(c_across(where(is.numeric)))) %>%
                           ungroup() %>%
                           mutate_if(is.numeric, list(~ round(100*./total, 1))) %>%
                           select(-total) %>%
                           rename("Batter Side" = BatterSide, "Count Type" = CountType) %>%
                           datatable(options = list(pageLength = 14))
                         }
                       })
      })
    
    
}

shinyApp(ui, server, options = list(height = 920, width = 980))

# Tab ideas:
# Game summaries(Make it plotly interactive?, also add colors for percentiles of metrics), player profiles(Add pitch tunneling?), pitcher comps, thresholds(pitches above speed or above a certain location), add in hitters eventually, 
# Once we get data for all schools, batter vs pitcher matchups for scouting reports, xStats and WAR
```

