---
title: "Visualizations for the dashboard"
author: "Samuel Brown"
date: "2023-03-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(ggpubr)
library(kableExtra)
```

```{r}
### Read in data
#files <- list.files(pattern = "*.csv")
#games <- lapply(files, read.csv, header = TRUE) 

#allPitches <- bind_rows(games)

allPitches <- read.csv("2023 Season Data.csv")
```

# Pitch types
```{r}
### Make pitch type table
allPitches %>%
  filter(PitchCall != "",
         TaggedPitchType != "",
         Pitcher == "Edgington, Brian") %>%
  group_by(Pitcher, TaggedPitchType) %>%
  summarize(Velo = paste(round(quantile(RelSpeed, .25), 1), 
                         "-",
                        round(quantile(RelSpeed, .75), 1)),
            'Total Pitches' = n(),
            Strikes = sum(PitchCall %in% c("StrikeCalled", "StrikeSwinging", "FoulBall", "InPlay")),
            Balls = sum(PitchCall %in% c("BallCalled", "HitByPitch", "BallinDirt", "BallIntentional")),
            Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
            Takes = sum(PitchCall %in% c("StrikeCalled", "BallCalled", "HitByPitch", "BallinDirt")),
            SwStr = sum(PitchCall == "StrikeSwinging"),
            WhiffPerc = 100*round(SwStr/Swings, 3),
            HR = sum(PlayResult == "HomeRun"),
            BABIP = (sum(PlayResult %in% c("Single", "Double", "Triple"))/
              sum(PlayResult %in% c("Single", "Double", "Triple", "Out", "Error", "FieldersChoice") | 
                    (TaggedHitType == "Bunt" & PlayResult == "Sacrifice"))) %>% round(3),
            .groups = "keep") %>%
  rename(Name = Pitcher, 'Pitch Type' = TaggedPitchType) %>%
  kable() %>%
  kable_styling(position = 'center')
```

```{r}
# Pie charts for swing decisions and swing results
ggarrange(allPitches %>%
            filter(PitchCall != "",
            TaggedPitchType != "",
            Pitcher == "Edgington, Brian",
            TaggedPitchType == "Fastball") %>%
            group_by(Pitcher, TaggedPitchType) %>%
            summarize(Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
                      Takes = sum(PitchCall %in% c("StrikeCalled", "BallCalled", "HitByPitch", "BallinDirt")),
                      .groups = "keep") %>%
            ungroup() %>%
            select(Swings, Takes) %>%
            t() %>%
            as.data.frame() %>%
            mutate(vars = rownames(.))%>%
            arrange(desc(vars)) %>%
            mutate(V1 = na_if(V1, 0),
                   prop = 100*V1/sum(V1),
                   ypos = cumsum(prop)-0.5*prop) %>%
            na.omit() %>%
            ggplot(aes(x = "", y = prop, fill = vars)) +
              geom_bar(stat = "identity", width = 1, color = "white") +
              coord_polar("y", start = 0) +
              labs(title = "Swing decisions") +
              theme_void() +
              theme(legend.title = element_blank(),
                    plot.title = element_text(size = 13)) +
              geom_text(aes(y = ypos, label = V1), color = "white", size = 4.75) +
              scale_fill_manual(values = c(Swings = "#181C90", Takes = "#F78707"),
                                labels = c("Swings", "Takes")),
          
          
          allPitches %>%
            filter(PitchCall != "",
            TaggedPitchType != "",
            Pitcher == "Edgington, Brian",
            TaggedPitchType == "Fastball") %>%
            group_by(Pitcher, TaggedPitchType) %>%
            summarize(Foul = sum(PitchCall == "FoulBall"),
                      BIP = sum(PitchCall == "InPlay"),
                      SwStr = sum(PitchCall == "StrikeSwinging"),
                      .groups = "keep") %>%
            ungroup() %>%
            select(Foul, BIP, SwStr) %>%
            t() %>%
            as.data.frame() %>%
            mutate(vars = rownames(.))%>%
            arrange(desc(vars)) %>%
            mutate(V1 = na_if(V1, 0),
                   prop = 100*V1/sum(V1),
                   ypos = cumsum(prop)-0.5*prop) %>%
            na.omit() %>%
            ggplot(aes(x = "", y = prop, fill = vars)) +
              geom_bar(stat = "identity", width = 1, color = "white") +
              coord_polar("y", start = 0) +
              labs(title = "Swings") +
              theme_void() +
              theme(legend.title = element_blank(),
                    plot.title = element_text(size = 13)) +
              geom_text(aes(y = ypos, label = V1), color = "white", size = 4.75) +
              scale_fill_manual(values = c(Foul = "#181C90", BIP = "#AEB7B3", SwStr = "#F78707"),
                                labels = c("In Play", "Foul", "Swinging Strike")),
      ncol = 2, widths = c(1, 1.12))
```


```{r}
# Make pitch location by pitch type plot
allPitches %>%
  filter(PitchCall != "",
         TaggedPitchType != "",
         Pitcher == "Edgington, Brian") %>%
  ggplot(aes(x = PlateLocSide, y = PlateLocHeight)) +
  geom_point(aes(color = RelSpeed), na.rm = TRUE) +
  xlim(-2.5, 2.5) +
  theme_bw() +
  labs(y = "Pitch Height(ft)", x = "Pitch Horizontal Location(ft)", color = "Velocity") +
  geom_path(data = data.frame(x = c(-.95, -.95, .95, .95, -.95),
                              y = c(1.6, 3.5, 3.5, 1.6, 1.6)), 
            aes(x = x, y = y)) +
  scale_color_gradient(low = "#181C90", high = "#F78707") +
  facet_grid(. ~ TaggedPitchType) +
  coord_equal()
```

# Counts
```{r}
### Make pitch type table
allPitches %>%
  filter(PitchCall != "",
         TaggedPitchType != "",
         Pitcher == "Edgington, Brian") %>%
  mutate(Count = paste(Balls, "-", Strikes, sep = "")) %>%
  group_by(Pitcher, Count) %>%
  summarize('Total Pitches' = n(),
            Strikes = sum(PitchCall %in% c("StrikeCalled", "StrikeSwinging", "FoulBall", "InPlay")),
            Balls = sum(PitchCall %in% c("BallCalled", "HitByPitch", "BallinDirt", "BallIntentional")),
            Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
            Takes = sum(PitchCall %in% c("StrikeCalled", "BallCalled", "HitByPitch", "BallinDirt")),
            SwStr = sum(PitchCall == "StrikeSwinging"),
            WhiffPerc = 100*round(SwStr/Swings, 3),
            HR = sum(PlayResult == "HomeRun"),
            BABIP = (sum(PlayResult %in% c("Single", "Double", "Triple"))/
              sum(PlayResult %in% c("Single", "Double", "Triple", "Out", "Error", "FieldersChoice") | 
                    (TaggedHitType == "Bunt" & PlayResult == "Sacrifice"))) %>% round(3),
            .groups = "keep") %>%
  rename(Name = Pitcher) %>%
  kable() %>%
  kable_styling(position = 'center')
```

```{r}
# Pie chart for a count
ggarrange(allPitches %>%
            mutate(Count = paste(Balls, "-", Strikes, sep = "")) %>%
            filter(PitchCall != "",
            Pitcher == "Edgington, Brian",
            Count == "0-0") %>%
            group_by(Pitcher, Count) %>%
            summarize(Swings = sum(PitchCall %in% c("FoulBall", "InPlay", "StrikeSwinging")),
                      Takes = sum(PitchCall %in% c("StrikeCalled", "BallCalled", "HitByPitch", "BallinDirt")),
                      .groups = "keep") %>%
            ungroup() %>%
            select(Swings, Takes) %>%
            t() %>%
            as.data.frame() %>%
            mutate(vars = rownames(.))%>%
            arrange(desc(vars)) %>%
            mutate(V1 = na_if(V1, 0),
                   prop = 100*V1/sum(V1),
                   ypos = cumsum(prop)-0.5*prop) %>%
            na.omit() %>%
            ggplot(aes(x = "", y = prop, fill = vars)) +
              geom_bar(stat = "identity", width = 1, color = "white") +
              coord_polar("y", start = 0) +
              labs(title = "Swing decisions") +
              theme_void() +
              theme(legend.title = element_blank(),
                    plot.title = element_text(size = 13)) +
              geom_text(aes(y = ypos, label = V1), color = "white", size = 4.75) +
              scale_fill_manual(values = c(Swings = "#181C90", Takes = "#F78707"),
                                labels = c("Swings", "Takes")),
          
          
          allPitches %>%
            mutate(Count = paste(Balls, "-", Strikes, sep = "")) %>%
            filter(PitchCall != "",
            Pitcher == "Edgington, Brian",
            Count == "0-0") %>%
            group_by(Pitcher, Count) %>%
            summarize(Foul = sum(PitchCall == "FoulBall"),
                      BIP = sum(PitchCall == "InPlay"),
                      SwStr = sum(PitchCall == "StrikeSwinging"),
                      .groups = "keep") %>%
            ungroup() %>%
            select(Foul, BIP, SwStr) %>%
            t() %>%
            as.data.frame() %>%
            mutate(vars = rownames(.))%>%
            arrange(desc(vars)) %>%
            mutate(V1 = na_if(V1, 0),
                   prop = 100*V1/sum(V1),
                   ypos = cumsum(prop)-0.5*prop) %>%
            na.omit() %>%
            ggplot(aes(x = "", y = prop, fill = vars)) +
              geom_bar(stat = "identity", width = 1, color = "white") +
              coord_polar("y", start = 0) +
              labs(title = "Swings") +
              theme_void() +
              theme(legend.title = element_blank(),
                    plot.title = element_text(size = 13)) +
              geom_text(aes(y = ypos, label = V1), color = "white", size = 4.75) +
              scale_fill_manual(values = c(Foul = "#181C90", BIP = "#AEB7B3", SwStr = "#F78707"),
                                labels = c("In Play", "Foul", "Swinging Strike")),
      ncol = 2, widths = c(1, 1.12))
```

```{r}
# Make pitch location by count plot
allPitches %>%
  filter(PitchCall != "",
         TaggedPitchType != "",
         Pitcher == "Edgington, Brian",
         Balls == 3, 
         Strikes == 2) %>%
  ggplot(aes(x = PlateLocSide, y = PlateLocHeight)) +
  geom_point(aes(color = RelSpeed), na.rm = TRUE) +
  xlim(-2.5, 2.5) +
  theme_bw() +
  labs(y = "Pitch Height(ft)", x = "Pitch Horizontal Location(ft)", color = "Velocity") +
  geom_path(data = data.frame(x = c(-.95, -.95, .95, .95, -.95),
                              y = c(1.6, 3.5, 3.5, 1.6, 1.6)), 
            aes(x = x, y = y)) +
  scale_color_gradient(low = "#181C90", high = "#F78707") 
```

# Brooks baseball tables
```{r}
# Trajectory and movement
allPitches %>%
  filter(PitchCall != "",
         TaggedPitchType != "",
         Pitcher == "Edgington, Brian") %>%
  group_by(Pitcher, TaggedPitchType) %>%
  summarize('Times Thrown' = n(),
            Velo = paste(round(quantile(RelSpeed, .25), 1), 
                         "-",
                        round(quantile(RelSpeed, .75), 1)),
            'Vertical Break' = round(mean(InducedVertBreak), 2),
            'Horizontal Break' = round(mean(HorzBreak), 2),
            'Vertical Release' = round(mean(RelHeight), 2),
            'Horizontal Release' = round(mean(RelSide), 2),
            .groups = "keep") %>%
  rename(Name = Pitcher, 'Pitch Type' = TaggedPitchType) %>%
  kable() %>%
  kable_styling(position = 'center')

```

```{r}
# Pitch Usage
allPitches %>%
  filter(Pitcher == "Edgington, Brian") %>%
  mutate(CountType = case_when(
    Balls == 0 & Strikes == 0 ~ "All Counts, Even, First Pitch",
    Balls == Strikes & Strikes != 2 ~ "All Counts, Even",
    Balls == Strikes & Strikes == 2 ~ "All Counts, Even, Two Strikes",
    
    Balls > Strikes & Strikes != 2 ~ "All Counts, Batter Ahead",
    Balls > Strikes & Strikes == 2 ~ "All Counts, Full Count",
    
    Balls < Strikes & Strikes != 2 ~ "All Counts, Pitcher Ahead",
    Balls < Strikes & Strikes == 2 ~ "All Counts, Pitcher Ahead, Two Strikes"
  ))  %>%
  separate_rows(CountType, sep = ", ") %>%
  group_by(BatterSide, CountType, TaggedPitchType) %>%
  summarize(ct = n()) %>%
  ungroup() %>%
  pivot_wider(names_from = TaggedPitchType, values_from = ct) %>%
  replace(is.na(.), 0) %>%
  rowwise() %>%
  mutate(total = sum(c_across(where(is.numeric)))) %>%
  ungroup() %>%
  mutate_if(is.numeric, list(~ round(100*./total, 1))) %>%
  select(-total)
```




# Visualize a single pitch
```{r}


```

